#!/usr/bin/env bash
declare -a archs=(armv7 i386 x86_64 arm64)
declare libdir=$1
if [ -z "$libdir" ]; then
  echo >&2 "Missing lib directory"
  exit 1
elif ! [ -d "$libdir" ]; then
  echo >&2 "Invalid lib directory"
  exit 1
fi

for lib in $libdir/*.a; do
  for a in ${archs[@]}; do
    out="$a/$(basename $lib)"

    cmd1="lipo -thin $a $lib -output $out"
    cmd2="test -f '$out' && ar -x '$out'"

    if [[ "dry" =~ "$2" ]]; then
      echo $cmd1
      echo $cmd2
      echo
    else
      $cmd1
      $cmd2
    fi
  done
done
